---
- name: Config office1Server
  hosts: all
  become: true

  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true

    - name: Install packages
      ansible.builtin.apt:
        name:
          - vim
          - traceroute

    # --- Static routes

    - name: Set default route to office1Router
      ansible.builtin.copy:
        src: files/office1Server-route.yaml
        dest: /etc/netplan/50-vagrant.yaml
        owner: root
        group: root
        mode: "0644"

    - name: Apply netplan
      ansible.builtin.shell: netplan apply
